import { defineType, defineField } from 'sanity'

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  icon: () => '⚙️',
  fields: [
    defineField({ name: 'companyName', title: 'Company Name', type: 'string' }),
    defineField({ name: 'founded', title: 'Year Founded', type: 'number', description: 'e.g. 2022' }),
    defineField({ name: 'logo', title: 'Logo', type: 'image', options: { hotspot: true } }),
    defineField({ name: 'phone', title: 'Phone Number', type: 'string' }),
    defineField({ name: 'email', title: 'Email Address', type: 'string' }),
    defineField({
      name: 'whatsapp',
      title: 'WhatsApp Number',
      type: 'string',
      description: 'Digits only, no + or spaces — used for wa.me links. e.g. "255768500555"',
    }),
    defineField({ name: 'address', title: 'Street Address', type: 'string' }),
    defineField({ name: 'poBox', title: 'P.O. Box', type: 'string' }),
    defineField({ name: 'city', title: 'City', type: 'string' }),
    defineField({ name: 'country', title: 'Country', type: 'string' }),
    defineField({
      name: 'regions',
      title: 'Active Regions / Branches',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Branch cities where the company operates, e.g. "Dar es Salaam", "Mbeya".',
    }),
    defineField({
      name: 'businessHours',
      title: 'Business Hours',
      type: 'text',
      rows: 3,
      description: 'e.g. "Monday – Friday: 8:00 AM – 5:00 PM\\nSaturday: 8:00 AM – 1:00 PM"',
    }),
    defineField({
      name: 'shopPageTitle',
      title: 'Shop Page — Heading',
      type: 'string',
      description: 'Main heading shown on the Product Catalog page. Defaults to "Quality Materials from [Company Name]".',
    }),
    defineField({
      name: 'shopPageSubtitle',
      title: 'Shop Page — Subtitle',
      type: 'text',
      rows: 2,
      description: 'Subtitle paragraph shown beneath the shop page heading.',
    }),
    defineField({
      name: 'socialLinks',
      title: 'Social Links',
      type: 'object',
      fields: [
        defineField({ name: 'facebook', title: 'Facebook URL', type: 'url' }),
        defineField({ name: 'twitter', title: 'Twitter / X URL', type: 'url' }),
        defineField({ name: 'instagram', title: 'Instagram URL', type: 'url' }),
        defineField({ name: 'linkedin', title: 'LinkedIn URL', type: 'url' }),
      ],
    }),
    defineField({
      name: 'erpIntegration',
      title: 'ERP & Catalog Integration',
      type: 'object',
      fields: [
        defineField({
          name: 'catalogUrl',
          title: 'Product Catalog URL',
          type: 'url',
          description: 'Link to the ERP-generated product catalog (e.g. https://comal-group.com/thlcatalog/1/4/). Update this whenever the ERP generates a new catalog link.',
        }),
        defineField({
          name: 'catalogLabel',
          title: 'Catalog Button Label',
          type: 'string',
          initialValue: 'View Full Catalog',
          description: 'The label shown on the catalog CTA button.',
        }),
        defineField({
          name: 'erpApiEnabled',
          title: 'ERP API Sync Enabled',
          type: 'boolean',
          initialValue: false,
          description: 'When enabled, product data will be pulled from the ERP API instead of manually entered Sanity records.',
        }),
        defineField({
          name: 'erpLastSyncedAt',
          title: 'Last ERP Sync',
          type: 'datetime',
          readOnly: true,
          description: 'Timestamp of the last successful ERP data sync. Updated automatically.',
        }),
      ],
    }),
  ],
  preview: {
    select: { title: 'companyName' },
  },
})
